name: Pripravi Arhive

on:
  push:
    branches: [ "gh-actions" ]
    paths-ignore:
      - '*.zip'
  pull_request:
    branches: [ "gh-actions" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lunarstarlight/fmfdelo-texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Pripravi arhive
        run : |
          git config --global --add safe.directory /__w/fmfdelo/fmfdelo
          cd predloge
          for dirname in $(ls); do
              if [ -d "$dirname" ]; then
                  git clean -Xdf
                  basename="Priimek-Vpisna-Leto"
                  texname=$basename.tex
                  pdfname=$basename.pdf
                  zipname=../../arhivi/$dirname.zip

                  echo "Compiling $dirname"
                  cd $dirname
                  zip -r $zipname *
                  latexmk -pdf $texname
                  verapdf -f 2b $pdfname
                  zip $zipname $pdfname

                  git clean -Xdf
                  cd ..
              fi
            cd ..
          done
      # - name: Semantic Release
      #   uses: wow-actions/release-github-action@v2
      #   with:
      #     dry-run: true
      #     branches: gh-actions
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GIT_AUTHOR_NAME: ${{ env.BOT_NAME }}[bot]
      #     GIT_AUTHOR_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com
      #     GIT_COMMITTER_NAME: ${{ env.BOT_NAME }}[bot]
      #     GIT_COMMITTER_EMAIL: ${{ env.BOT_NAME }}[bot]@users.noreply.github.com
      - name: Commit archives
        run: |
          git config --local user.name "${{ env.BOT_NAME }}[bot]"
          git config --local user.email "${{ env.BOT_NAME }}[bot]@users.noreply.github.com"
          git add -f arhivi/*.zip
          git commit -m "Posodobi arhive [skip ci]"
      - name: Objavi arhive
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

