name: Pripravi Arhive

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: pripravi-arhive.sh
        run: |
          set -e
          cd predloge
          for dirname in *; do
            if [ -d "$dirname" ]; then
              git clean -Xdf
              basename="Priimek-Vpisna-Leto"
              texname=$basename.tex
              pdfname=$basename.pdf
              zipname=../../arhivi/$dirname.zip

              cd $dirname
              zip -r $zipname *
              latexmk -pdf $texname
              verapdf $pdfname
              zip $zipname $pdfname

              git clean -Xdf
              cd ..
            fi
          done
