name: Pripravi Arhive

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pripravi-arhive.sh
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./pripravi-arhive.sh
