name: Pripravi Arhive

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install verapdf
        run: |
          sudo apt-get install flatpak
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          run: flatpak install -y --noninteractive flathub org.verapdf.veraPDF
      #- name: pripravi-arhive.sh
      #  uses: dante-ev/latex-action@latest
      #  with:
      #    entrypoint: ./pripravi-arhive.sh
