name: Pripravi Arhive

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '*.pdf'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lunarstarlight/fmfdelo-texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pripravi arhive
        run : |
          # dbus-daemon --system
          # flatpak repair --system --reinstall-all
          # flatpak run --command=verapdf org.verapdf.veraPDF --help
          git config --global --add safe.directory /__w/fmfdelo/fmfdelo
          cd predloge
          for dirname in $(ls); do
              if [ -d "$dirname" ]; then
                  git clean -Xdf
                  basename="Priimek-Vpisna-Leto"
                  texname=$basename.tex
                  pdfname=$basename.pdf
                  zipname=../../arhivi/$dirname.zip

                  echo "Compiling $dirname"
                  cd $dirname
                  zip -r $zipname *
                  latexmk -pdf $texname
                  verapdf -f 2b $pdfname
                  zip $zipname $pdfname

                  git clean -Xdf
                  cd ..
              fi
          done

